{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOTMY7CFzfzrdtfnEmEIvtE",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/FolatheDuckofDuckingburg/VampireBCI/blob/main/VampireBCI.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 5,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "T_uKnk1YJYDv",
        "outputId": "b4d20b70-c1a0-4020-848d-317d416f75a4"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Searching for EDFs under /content ...\n",
            "Found 74 EDF files\n",
            "\n",
            "  M_04_SE001_ADdiff_Test01.edf: 6 trials  acc=83.3%  L_mean=7.958s  L_std=2.060s\n",
            "  M_04_SE001_ADdiff_Test02.edf: 6 trials  acc=83.3%  L_mean=7.667s  L_std=2.088s\n",
            "  M_04_SE001_ADdiff_Test03.edf: 6 trials  acc=100.0%  L_mean=9.438s  L_std=3.260s\n",
            "  M_04_SE001_ADdiff_Test04.edf: 6 trials  acc=100.0%  L_mean=5.688s  L_std=1.201s\n",
            "  M_04_SE001_ADdiff_Test05.edf: 6 trials  acc=100.0%  L_mean=7.146s  L_std=0.780s\n",
            "  M_05_SE001_ADdiff_Test01.edf: 6 trials  acc=66.7%  L_mean=6.646s  L_std=2.312s\n",
            "  M_05_SE001_ADdiff_Test02.edf: 6 trials  acc=100.0%  L_mean=4.729s  L_std=1.465s\n",
            "  M_05_SE001_ADdiff_Test03.edf: 6 trials  acc=66.7%  L_mean=7.250s  L_std=1.421s\n",
            "  M_05_SE001_ADdiff_Test04.edf: 6 trials  acc=50.0%  L_mean=9.708s  L_std=3.537s\n",
            "  M_05_SE001_ADdiff_Test05.edf: 6 trials  acc=66.7%  L_mean=7.625s  L_std=1.734s\n",
            "  M_06_SE001_ADdiff_Test01.edf: 6 trials  acc=83.3%  L_mean=10.250s  L_std=2.178s\n",
            "  M_06_SE001_ADdiff_Test02.edf: 6 trials  acc=83.3%  L_mean=10.854s  L_std=3.624s\n",
            "  M_06_SE001_ADdiff_Test03.edf: 6 trials  acc=83.3%  L_mean=13.146s  L_std=2.300s\n",
            "  M_06_SE001_ADdiff_Test04.edf: 6 trials  acc=66.7%  L_mean=10.812s  L_std=2.463s\n",
            "  M_06_SE001_ADdiff_Test05.edf: 6 trials  acc=83.3%  L_mean=13.021s  L_std=2.217s\n",
            "  M_09_SE001_ADdiff_Test01.edf: 6 trials  acc=83.3%  L_mean=7.604s  L_std=2.772s\n",
            "  M_09_SE001_ADdiff_Test02.edf: 6 trials  acc=66.7%  L_mean=7.979s  L_std=3.804s\n",
            "  M_09_SE001_ADdiff_Test03.edf: 6 trials  acc=83.3%  L_mean=12.167s  L_std=3.598s\n",
            "  M_09_SE001_ADdiff_Test04.edf: 6 trials  acc=50.0%  L_mean=11.479s  L_std=3.159s\n",
            "  M_09_SE001_ADdiff_Test05.edf: 6 trials  acc=16.7%  L_mean=11.271s  L_std=4.247s\n",
            "  M_10_SE001_ADdiff_Test01.edf: 6 trials  acc=83.3%  L_mean=5.312s  L_std=1.485s\n",
            "  M_10_SE001_ADdiff_Test02.edf: 6 trials  acc=100.0%  L_mean=4.792s  L_std=0.993s\n",
            "  M_10_SE001_ADdiff_Test03.edf: 6 trials  acc=100.0%  L_mean=5.958s  L_std=1.431s\n",
            "  M_10_SE001_ADdiff_Test04.edf: 6 trials  acc=100.0%  L_mean=4.667s  L_std=0.914s\n",
            "  M_10_SE001_ADdiff_Test05.edf: 6 trials  acc=100.0%  L_mean=5.021s  L_std=1.350s\n",
            "  M_11_SE001_ADdiff_Test01.edf: 6 trials  acc=83.3%  L_mean=9.771s  L_std=4.523s\n",
            "  M_11_SE001_ADdiff_Test02.edf: 6 trials  acc=66.7%  L_mean=8.938s  L_std=2.000s\n",
            "  M_11_SE001_ADdiff_Test03.edf: 6 trials  acc=83.3%  L_mean=7.167s  L_std=1.963s\n",
            "  M_11_SE001_ADdiff_Test04.edf: 6 trials  acc=100.0%  L_mean=6.125s  L_std=1.768s\n",
            "  M_11_SE001_ADdiff_Test05.edf: 6 trials  acc=83.3%  L_mean=10.625s  L_std=4.241s\n",
            "  M_12_SE001_ADdiff_Test01.edf: 6 trials  acc=100.0%  L_mean=4.417s  L_std=0.645s\n",
            "  M_12_SE001_ADdiff_Test02.edf: 6 trials  acc=100.0%  L_mean=4.979s  L_std=1.074s\n",
            "  M_12_SE001_ADdiff_Test03.edf: 6 trials  acc=100.0%  L_mean=4.771s  L_std=1.674s\n",
            "  M_12_SE001_ADdiff_Test04.edf: 6 trials  acc=100.0%  L_mean=4.396s  L_std=1.047s\n",
            "  M_12_SE001_ADdiff_Test05.edf: 6 trials  acc=83.3%  L_mean=5.417s  L_std=1.298s\n",
            "  M_13_SE001_ADdiff_Test01.edf: 6 trials  acc=100.0%  L_mean=4.250s  L_std=1.202s\n",
            "  M_13_SE001_ADdiff_Test02.edf: 6 trials  acc=83.3%  L_mean=2.958s  L_std=0.714s\n",
            "  M_13_SE001_ADdiff_Test03.edf: 6 trials  acc=100.0%  L_mean=4.146s  L_std=1.071s\n",
            "  M_13_SE001_ADdiff_Test04.edf: 6 trials  acc=83.3%  L_mean=3.188s  L_std=0.505s\n",
            "  M_13_SE001_ADdiff_Test05.edf: 6 trials  acc=100.0%  L_mean=3.792s  L_std=0.650s\n",
            "  M_14_SE001_ADdiff_Test01.edf: 6 trials  acc=100.0%  L_mean=4.542s  L_std=1.166s\n",
            "  M_14_SE001_ADdiff_Test02.edf: 6 trials  acc=100.0%  L_mean=6.312s  L_std=1.905s\n",
            "  M_14_SE001_ADdiff_Test03.edf: 6 trials  acc=100.0%  L_mean=5.750s  L_std=3.008s\n",
            "  M_14_SE001_ADdiff_Test04.edf: 6 trials  acc=100.0%  L_mean=5.000s  L_std=1.419s\n",
            "  M_14_SE001_ADdiff_Test05.edf: 6 trials  acc=100.0%  L_mean=5.188s  L_std=0.821s\n",
            "  M_15_SE001_ADdiff_Test01.edf: 6 trials  acc=50.0%  L_mean=9.083s  L_std=1.418s\n",
            "  M_15_SE001_ADdiff_Test02.edf: 6 trials  acc=50.0%  L_mean=9.562s  L_std=2.574s\n",
            "  M_15_SE001_ADdiff_Test03.edf: 6 trials  acc=66.7%  L_mean=9.583s  L_std=3.997s\n",
            "  M_15_SE001_ADdiff_Test04.edf: 6 trials  acc=66.7%  L_mean=9.625s  L_std=3.842s\n",
            "  M_15_SE001_ADdiff_Test05.edf: 6 trials  acc=66.7%  L_mean=8.146s  L_std=3.600s\n",
            "  M_16_SE001_ADdiff_Test01.edf: 6 trials  acc=100.0%  L_mean=6.979s  L_std=2.088s\n",
            "  M_16_SE001_ADdiff_Test02.edf: 6 trials  acc=50.0%  L_mean=7.812s  L_std=3.336s\n",
            "  M_16_SE001_ADdiff_Test03.edf: 6 trials  acc=66.7%  L_mean=5.083s  L_std=1.066s\n",
            "  M_16_SE001_ADdiff_Test04.edf: 6 trials  acc=100.0%  L_mean=6.688s  L_std=1.083s\n",
            "  M_16_SE001_ADdiff_Test05.edf: 6 trials  acc=100.0%  L_mean=7.771s  L_std=2.499s\n",
            "  M_17_SE001_ADdiff_Test01.edf: 6 trials  acc=100.0%  L_mean=3.917s  L_std=1.281s\n",
            "  M_17_SE001_ADdiff_Test02.edf: 6 trials  acc=83.3%  L_mean=4.000s  L_std=1.976s\n",
            "  M_17_SE001_ADdiff_Test03.edf: 6 trials  acc=100.0%  L_mean=4.229s  L_std=1.350s\n",
            "  M_17_SE001_ADdiff_Test04.edf: 6 trials  acc=100.0%  L_mean=4.729s  L_std=1.357s\n",
            "  M_17_SE001_ADdiff_Test05.edf: 6 trials  acc=100.0%  L_mean=5.125s  L_std=1.630s\n",
            "  M_18_SE001_ADdiff_Test01.edf: 6 trials  acc=100.0%  L_mean=5.354s  L_std=0.464s\n",
            "  M_18_SE001_ADdiff_Test02.edf: 6 trials  acc=100.0%  L_mean=3.854s  L_std=1.273s\n",
            "  M_18_SE001_ADdiff_Test03.edf: 6 trials  acc=83.3%  L_mean=4.625s  L_std=1.423s\n",
            "  M_18_SE001_ADdiff_Test04.edf: 6 trials  acc=100.0%  L_mean=4.000s  L_std=0.570s\n",
            "  M_18_SE001_ADdiff_Test05.edf: 6 trials  acc=100.0%  L_mean=4.833s  L_std=1.054s\n",
            "  M_19_SE001_ADdiff_Test01.edf: 6 trials  acc=66.7%  L_mean=7.917s  L_std=3.895s\n",
            "  M_19_SE001_ADdiff_Test02.edf: 6 trials  acc=83.3%  L_mean=9.417s  L_std=2.276s\n",
            "  M_19_SE001_ADdiff_Test03.edf: 6 trials  acc=66.7%  L_mean=7.688s  L_std=2.497s\n",
            "  M_19_SE001_ADdiff_Test05.edf: 6 trials  acc=50.0%  L_mean=8.521s  L_std=4.012s\n",
            "  M_20_SE001_ADdiff_Test01.edf: 6 trials  acc=66.7%  L_mean=10.229s  L_std=2.754s\n",
            "  M_20_SE001_ADdiff_Test02.edf: 6 trials  acc=83.3%  L_mean=7.917s  L_std=2.560s\n",
            "  M_20_SE001_ADdiff_Test03.edf: 6 trials  acc=50.0%  L_mean=8.792s  L_std=3.469s\n",
            "  M_20_SE001_ADdiff_Test04.edf: 6 trials  acc=50.0%  L_mean=7.250s  L_std=3.950s\n",
            "  M_20_SE001_ADdiff_Test05.edf: 6 trials  acc=66.7%  L_mean=9.812s  L_std=1.900s\n",
            "\n",
            "============================================================\n",
            "POOLED: 444 trials from 74 files, 15 subjects\n",
            "============================================================\n",
            "Accuracy:   82.9%  (368/444)\n",
            "L mean:     7.0602 s\n",
            "L std:      3.3209 s\n",
            "L min/max:  1.8750 / 15.0000 s\n",
            "\n",
            "Per subject:\n",
            "  M_04: n=  30  acc= 93.3%  L_mean=7.579s  L_std=2.279s\n",
            "  M_05: n=  30  acc= 70.0%  L_mean=7.192s  L_std=2.642s\n",
            "  M_06: n=  30  acc= 80.0%  L_mean=11.617s  L_std=2.724s\n",
            "  M_09: n=  30  acc= 60.0%  L_mean=10.100s  L_std=3.829s\n",
            "  M_10: n=  30  acc= 96.7%  L_mean=5.150s  L_std=1.257s\n",
            "  M_11: n=  30  acc= 83.3%  L_mean=8.525s  L_std=3.371s\n",
            "  M_12: n=  30  acc= 96.7%  L_mean=4.796s  L_std=1.176s\n",
            "  M_13: n=  30  acc= 93.3%  L_mean=3.667s  L_std=0.961s\n",
            "  M_14: n=  30  acc=100.0%  L_mean=5.358s  L_std=1.810s\n",
            "  M_15: n=  30  acc= 60.0%  L_mean=9.200s  L_std=3.058s\n",
            "  M_16: n=  30  acc= 83.3%  L_mean=6.867s  L_std=2.273s\n",
            "  M_17: n=  30  acc= 96.7%  L_mean=4.400s  L_std=1.505s\n",
            "  M_18: n=  30  acc= 96.7%  L_mean=4.533s  L_std=1.108s\n",
            "  M_19: n=  24  acc= 66.7%  L_mean=8.385s  L_std=3.122s\n",
            "  M_20: n=  30  acc= 63.3%  L_mean=8.800s  L_std=3.020s\n",
            "\n",
            "Subject IDs present: [4, 5, 6, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]\n",
            "\n",
            "Saved to pooled_trials_full.csv\n"
          ]
        }
      ],
      "source": [
        "\"\"\"\n",
        "VampireBCI — final\n",
        "Extracts trial-level (L, Y) data from bigP3BCI EDFs.\n",
        "Handles M_04 through M_25 (M_08 does not exist).\n",
        "\"\"\"\n",
        "\n",
        "import pyedflib\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import glob\n",
        "import os\n",
        "import zipfile\n",
        "import re\n",
        "\n",
        "EVENT_CHANNELS = [\n",
        "    \"StimulusBegin\", \"DisplayResults\", \"CurrentTarget\",\n",
        "    \"SelectedTarget\", \"SelectedRow\", \"SelectedColumn\",\n",
        "    \"PhaseInSequence\", \"StimulusCode\", \"StimulusType\",\n",
        "]\n",
        "\n",
        "GRID_COLS = 8\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# Find EDFs anywhere under a root (case-insensitive, unzips first)\n",
        "# ============================================================\n",
        "def find_edfs(root=\"/content\"):\n",
        "    zips = glob.glob(os.path.join(root, \"**\", \"*.zip\"), recursive=True)\n",
        "    for z in zips:\n",
        "        try:\n",
        "            with zipfile.ZipFile(z) as zf:\n",
        "                zf.extractall(os.path.dirname(z))\n",
        "            print(f\"  unzipped: {os.path.basename(z)}\")\n",
        "        except Exception as e:\n",
        "            print(f\"  [skip zip] {z}: {e}\")\n",
        "\n",
        "    found = []\n",
        "    for p in glob.glob(os.path.join(root, \"**\", \"*\"), recursive=True):\n",
        "        if os.path.isfile(p) and p.lower().endswith(\".edf\"):\n",
        "            found.append(p)\n",
        "    return sorted(found)\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# EDF reading\n",
        "# ============================================================\n",
        "def read_edf(path):\n",
        "    f = pyedflib.EdfReader(path)\n",
        "    labels = f.getSignalLabels()\n",
        "    data = {}\n",
        "    fs = None\n",
        "    for name in EVENT_CHANNELS:\n",
        "        if name in labels:\n",
        "            idx = labels.index(name)\n",
        "            data[name] = f.readSignal(idx)\n",
        "            if fs is None:\n",
        "                fs = f.getSampleFrequency(idx)\n",
        "    ann = f.readAnnotations()\n",
        "    f.close()\n",
        "    if fs is None:\n",
        "        raise ValueError(\"no event channels found\")\n",
        "    return data, ann, fs\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# Helpers\n",
        "# ============================================================\n",
        "def decode_cell(cell_index):\n",
        "    \"\"\"cell = (row-1)*8 + col -> (row, col), 1-indexed.\"\"\"\n",
        "    if cell_index == 0:\n",
        "        return (0, 0)\n",
        "    row = (cell_index - 1) // GRID_COLS + 1\n",
        "    col = (cell_index - 1) % GRID_COLS + 1\n",
        "    return (row, col)\n",
        "\n",
        "\n",
        "def find_feedback_onsets(dr):\n",
        "    return np.where((dr[1:] == 1) & (dr[:-1] == 0))[0] + 1\n",
        "\n",
        "\n",
        "def find_flash_onsets(sb):\n",
        "    return np.where((sb[1:] == 1) & (sb[:-1] == 0))[0] + 1\n",
        "\n",
        "\n",
        "def find_selected_runs(st):\n",
        "    nz = np.where(st != 0)[0]\n",
        "    if len(nz) == 0:\n",
        "        return np.array([], dtype=int), np.array([], dtype=int)\n",
        "    breaks = np.where(np.diff(nz) > 1)[0]\n",
        "    starts = np.concatenate([[nz[0]], nz[breaks + 1]])\n",
        "    ends = np.concatenate([nz[breaks], [nz[-1]]])\n",
        "    return starts, ends\n",
        "\n",
        "\n",
        "def parse_filename(path):\n",
        "    \"\"\"\n",
        "    From 'M_05_SE001_ADdiff_Test01.edf' extract:\n",
        "      subject = 'M_05'\n",
        "      session = 'SE001'\n",
        "      test    = 'Test01'\n",
        "    \"\"\"\n",
        "    base = os.path.basename(path)\n",
        "    for ext in (\".edf\", \".EDF\"):\n",
        "        if base.endswith(ext):\n",
        "            base = base[: -len(ext)]\n",
        "            break\n",
        "    parts = base.split(\"_\")\n",
        "\n",
        "    subject = \"_\".join(parts[:2]) if len(parts) >= 2 else \"unknown\"\n",
        "    session = parts[2] if len(parts) >= 3 else \"unknown\"\n",
        "    test = parts[-1] if len(parts) >= 1 else \"unknown\"\n",
        "    return subject, session, test\n",
        "\n",
        "\n",
        "def subject_num(subject):\n",
        "    \"\"\"Extract numeric ID from 'M_XX'. Returns None if not parseable.\"\"\"\n",
        "    m = re.match(r\"M_(\\d+)\", subject)\n",
        "    return int(m.group(1)) if m else None\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# Extraction — one file\n",
        "# ============================================================\n",
        "def extract_file(path, verbose=True):\n",
        "    try:\n",
        "        data, ann, fs = read_edf(path)\n",
        "    except Exception as e:\n",
        "        if verbose:\n",
        "            print(f\"  [skip] {os.path.basename(path)}: {e}\")\n",
        "        return None\n",
        "\n",
        "    sb = data.get(\"StimulusBegin\")\n",
        "    dr = data.get(\"DisplayResults\")\n",
        "    st = data.get(\"SelectedTarget\")\n",
        "    ct = data.get(\"CurrentTarget\")\n",
        "\n",
        "    if sb is None or dr is None or st is None:\n",
        "        if verbose:\n",
        "            print(f\"  [skip] {os.path.basename(path)}: missing core channels\")\n",
        "        return None\n",
        "\n",
        "    fb_idx = find_feedback_onsets(dr)\n",
        "    fl_idx = find_flash_onsets(sb)\n",
        "    run_starts, run_ends = find_selected_runs(st)\n",
        "\n",
        "    if len(fb_idx) == 0 or len(run_starts) == 0:\n",
        "        if verbose:\n",
        "            print(f\"  [skip] {os.path.basename(path)}: \"\n",
        "                  f\"{len(fb_idx)} feedback, {len(run_starts)} selection runs\")\n",
        "        return None\n",
        "\n",
        "    n_trials = min(len(fb_idx), len(run_starts))\n",
        "    trials = []\n",
        "    prev_fb = -1\n",
        "\n",
        "    for k in range(n_trials):\n",
        "        tfb_i = fb_idx[k]\n",
        "        run_s, run_e = run_starts[k], run_ends[k]\n",
        "\n",
        "        sel_cell = int(st[run_s:run_e + 1].max())\n",
        "        sel_row, sel_col = decode_cell(sel_cell)\n",
        "\n",
        "        tgt = 0\n",
        "        if ct is not None:\n",
        "            win = ct[max(0, tfb_i - int(1.0 * fs)):tfb_i + 1]\n",
        "            nz = win[win != 0]\n",
        "            if len(nz):\n",
        "                tgt = int(nz[-1])\n",
        "\n",
        "        flashes = fl_idx[(fl_idx > prev_fb) & (fl_idx < tfb_i)]\n",
        "        if len(flashes) == 0:\n",
        "            prev_fb = tfb_i\n",
        "            continue\n",
        "        t0_i = int(flashes.min())\n",
        "\n",
        "        L = (tfb_i - t0_i) / fs\n",
        "        Y = 1 if (sel_cell != 0 and sel_cell == tgt) else 0\n",
        "\n",
        "        trials.append({\n",
        "            \"file\": os.path.basename(path),\n",
        "            \"trial\": k,\n",
        "            \"t0_s\": t0_i / fs,\n",
        "            \"tfb_s\": tfb_i / fs,\n",
        "            \"L_s\": L,\n",
        "            \"selected_cell\": sel_cell,\n",
        "            \"selected_row\": sel_row,\n",
        "            \"selected_col\": sel_col,\n",
        "            \"true_target\": tgt,\n",
        "            \"Y\": Y,\n",
        "            \"n_flashes\": int(len(flashes)),\n",
        "        })\n",
        "\n",
        "        prev_fb = tfb_i\n",
        "\n",
        "    if not trials:\n",
        "        return None\n",
        "\n",
        "    df = pd.DataFrame(trials)\n",
        "    subject, session, test = parse_filename(path)\n",
        "    df[\"subject\"] = subject\n",
        "    df[\"session\"] = session\n",
        "    df[\"test\"] = test\n",
        "\n",
        "    if verbose:\n",
        "        acc = df[\"Y\"].mean() * 100\n",
        "        print(f\"  {os.path.basename(path)}: {len(df)} trials  \"\n",
        "              f\"acc={acc:.1f}%  L_mean={df['L_s'].mean():.3f}s  \"\n",
        "              f\"L_std={df['L_s'].std():.3f}s\")\n",
        "\n",
        "    return df\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# Main\n",
        "# ============================================================\n",
        "def main(root=\"/content\", out_csv=\"pooled_trials_full.csv\"):\n",
        "    print(f\"Searching for EDFs under {root} ...\")\n",
        "    edfs = find_edfs(root)\n",
        "    print(f\"Found {len(edfs)} EDF files\\n\")\n",
        "\n",
        "    if not edfs:\n",
        "        print(\"Nothing to process.\")\n",
        "        return None\n",
        "\n",
        "    all_trials = []\n",
        "    skipped = []\n",
        "\n",
        "    for p in edfs:\n",
        "        r = extract_file(p)\n",
        "        if r is not None:\n",
        "            all_trials.append(r)\n",
        "        else:\n",
        "            skipped.append(os.path.basename(p))\n",
        "\n",
        "    if not all_trials:\n",
        "        print(\"\\nNo trials extracted.\")\n",
        "        return None\n",
        "\n",
        "    pooled = pd.concat(all_trials, ignore_index=True)\n",
        "\n",
        "    # Sort by subject number, then session, then test, so output is stable\n",
        "    pooled[\"_subj_num\"] = pooled[\"subject\"].apply(subject_num).fillna(999)\n",
        "    pooled = pooled.sort_values([\"_subj_num\", \"session\", \"test\", \"trial\"])\n",
        "    pooled = pooled.drop(columns=[\"_subj_num\"]).reset_index(drop=True)\n",
        "\n",
        "    pooled.to_csv(out_csv, index=False)\n",
        "\n",
        "    print()\n",
        "    print(\"=\" * 60)\n",
        "    print(f\"POOLED: {len(pooled)} trials from \"\n",
        "          f\"{pooled['file'].nunique()} files, \"\n",
        "          f\"{pooled['subject'].nunique()} subjects\")\n",
        "    print(\"=\" * 60)\n",
        "\n",
        "    n = len(pooled)\n",
        "    acc = pooled[\"Y\"].mean() * 100\n",
        "    print(f\"Accuracy:   {acc:.1f}%  ({int(pooled['Y'].sum())}/{n})\")\n",
        "    print(f\"L mean:     {pooled['L_s'].mean():.4f} s\")\n",
        "    print(f\"L std:      {pooled['L_s'].std():.4f} s\")\n",
        "    print(f\"L min/max:  {pooled['L_s'].min():.4f} / \"\n",
        "          f\"{pooled['L_s'].max():.4f} s\")\n",
        "\n",
        "    print()\n",
        "    print(\"Per subject:\")\n",
        "    for subj, g in pooled.groupby(\"subject\"):\n",
        "        print(f\"  {subj}: n={len(g):4d}  acc={g['Y'].mean()*100:5.1f}%  \"\n",
        "              f\"L_mean={g['L_s'].mean():.3f}s  \"\n",
        "              f\"L_std={g['L_s'].std():.3f}s\")\n",
        "\n",
        "    # Which subjects are in the new range?\n",
        "    nums = sorted(set(\n",
        "        subject_num(s) for s in pooled[\"subject\"].unique()\n",
        "        if subject_num(s) is not None\n",
        "    ))\n",
        "    print()\n",
        "    print(f\"Subject IDs present: {nums}\")\n",
        "\n",
        "    if skipped:\n",
        "        print()\n",
        "        print(f\"Skipped {len(skipped)} files:\")\n",
        "        for s in skipped[:20]:\n",
        "            print(f\"  - {s}\")\n",
        "        if len(skipped) > 20:\n",
        "            print(f\"  ... and {len(skipped) - 20} more\")\n",
        "\n",
        "    print()\n",
        "    print(f\"Saved to {out_csv}\")\n",
        "    return pooled\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# Run\n",
        "# ============================================================\n",
        "if __name__ == \"__main__\":\n",
        "    pooled = main(\"/content\")"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"\n",
        "NFOT — Final analysis for v4/v5.\n",
        "Input:  pooled_trials_full.csv\n",
        "Output: all statistics reported in the preprint.\n",
        "\"\"\"\n",
        "\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import statsmodels.api as sm\n",
        "import statsmodels.formula.api as smf\n",
        "from scipy import stats\n",
        "from sklearn.model_selection import LeaveOneGroupOut\n",
        "from sklearn.metrics import roc_auc_score, log_loss, brier_score_loss\n",
        "\n",
        "RNG = np.random.default_rng(42)\n",
        "CSV = \"pooled_trials_full.csv\"\n",
        "\n",
        "# ============================================================\n",
        "# Load\n",
        "# ============================================================\n",
        "df = pd.read_csv(CSV)\n",
        "print(f\"Loaded {len(df)} trials from {df['subject'].nunique()} subjects\")\n",
        "print(f\"Overall accuracy: {df['Y'].mean()*100:.1f}%\")\n",
        "print(f\"L mean={df['L_s'].mean():.3f}s  std={df['L_s'].std():.3f}s\")\n",
        "print()\n",
        "\n",
        "groups = df[\"subject\"]\n",
        "logo = LeaveOneGroupOut()\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# 1. Trial-level regressions (in-sample)\n",
        "# ============================================================\n",
        "print(\"=\" * 60)\n",
        "print(\"1. TRIAL-LEVEL REGRESSIONS (in-sample)\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "df[\"L_within\"] = df[\"L_s\"] - df.groupby(\"subject\")[\"L_s\"].transform(\"mean\")\n",
        "\n",
        "m1 = smf.logit(\"Y ~ L_s\", data=df).fit(disp=0)\n",
        "print(f\"  Pooled:          beta={m1.params['L_s']:+.4f}  p={m1.pvalues['L_s']:.4f}\")\n",
        "\n",
        "m2 = smf.logit(\"Y ~ L_s + C(subject)\", data=df).fit(disp=0)\n",
        "print(f\"  Subject FE:      beta={m2.params['L_s']:+.4f}  p={m2.pvalues['L_s']:.4f}\")\n",
        "\n",
        "m3 = sm.MixedLM.from_formula(\"Y ~ L_s\", groups=\"subject\", data=df).fit()\n",
        "print(f\"  Mixed model:     beta={m3.params['L_s']:+.4f}  p={m3.pvalues['L_s']:.4f}\")\n",
        "\n",
        "m4 = smf.logit(\"Y ~ L_within\", data=df).fit(disp=0)\n",
        "print(f\"  Within-subject:  beta={m4.params['L_within']:+.4f}  p={m4.pvalues['L_within']:.4f}\")\n",
        "print()\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# 2. Leave-one-subject-out validation\n",
        "# ============================================================\n",
        "print(\"=\" * 60)\n",
        "print(\"2. LEAVE-ONE-SUBJECT-OUT VALIDATION\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "betas, per_subj = [], []\n",
        "for tr, te in logo.split(df, groups=groups):\n",
        "    train = df.iloc[tr].copy()\n",
        "    test = df.iloc[te].copy()\n",
        "    train[\"L_within\"] = train[\"L_s\"] - train.groupby(\"subject\")[\"L_s\"].transform(\"mean\")\n",
        "    m = smf.logit(\"Y ~ L_within\", data=train).fit(disp=0)\n",
        "    betas.append(m.params[\"L_within\"])\n",
        "    per_subj.append({\n",
        "        \"subject\": test[\"subject\"].iloc[0],\n",
        "        \"n\": len(test),\n",
        "        \"n_correct\": int(test[\"Y\"].sum()),\n",
        "        \"n_incorrect\": int((1 - test[\"Y\"]).sum()),\n",
        "        \"beta\": m.params[\"L_within\"],\n",
        "    })\n",
        "\n",
        "betas = np.array(betas)\n",
        "print(f\"  LOSO beta:  {betas.mean():+.4f} ± {betas.std():.4f}\")\n",
        "print(f\"  Negative:   {(betas < 0).sum()}/{len(betas)}\")\n",
        "print()\n",
        "print(\"  Per held-out subject:\")\n",
        "for s in per_subj:\n",
        "    print(f\"    {s['subject']}: n={s['n']}  correct={s['n_correct']:2d}  \"\n",
        "          f\"incorrect={s['n_incorrect']:2d}  beta={s['beta']:+.4f}\")\n",
        "print()\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# 3. Subject-level correlations\n",
        "# ============================================================\n",
        "print(\"=\" * 60)\n",
        "print(\"3. SUBJECT-LEVEL CORRELATIONS\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "subj = df.groupby(\"subject\").agg(\n",
        "    n=(\"Y\", \"size\"),\n",
        "    acc=(\"Y\", \"mean\"),\n",
        "    L_mean=(\"L_s\", \"mean\"),\n",
        "    L_std=(\"L_s\", \"std\"),\n",
        ").reset_index()\n",
        "\n",
        "print(subj.to_string(index=False))\n",
        "print()\n",
        "\n",
        "r_mean, p_mean = stats.pearsonr(subj[\"L_mean\"], subj[\"acc\"])\n",
        "r_std, p_std = stats.pearsonr(subj[\"L_std\"], subj[\"acc\"])\n",
        "print(f\"  r(L_mean, acc) = {r_mean:+.3f}  p = {p_mean:.4f}\")\n",
        "print(f\"  r(L_std,  acc) = {r_std:+.3f}  p = {p_std:.4f}\")\n",
        "print(f\"  (Bonferroni threshold for 2 tests: p < {0.05/2:.4f})\")\n",
        "print()\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# 4. Partial correlation: does L_std survive L_mean?\n",
        "# ============================================================\n",
        "print(\"=\" * 60)\n",
        "print(\"4. PARTIAL CORRELATION (L_std controlling for L_mean)\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "X = sm.add_constant(subj[[\"L_mean\", \"L_std\"]])\n",
        "m_ols = sm.OLS(subj[\"acc\"], X).fit()\n",
        "print(m_ols.summary().tables[1])\n",
        "print()\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# 5. Tail splits\n",
        "# ============================================================\n",
        "print(\"=\" * 60)\n",
        "print(\"5. TAIL SPLITS\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "for q in [0.75, 0.90]:\n",
        "    thr = df[\"L_s\"].quantile(q)\n",
        "    top = df[df[\"L_s\"] >= thr]\n",
        "    rest = df[df[\"L_s\"] < thr]\n",
        "    table = [[int(top[\"Y\"].sum()), len(top) - int(top[\"Y\"].sum())],\n",
        "             [int(rest[\"Y\"].sum()), len(rest) - int(rest[\"Y\"].sum())]]\n",
        "    _, p = stats.fisher_exact(table)\n",
        "    print(f\"  q={q:.2f}  threshold={thr:.2f}s\")\n",
        "    print(f\"    top:  n={len(top):3d}  acc={top['Y'].mean()*100:.1f}%\")\n",
        "    print(f\"    rest: n={len(rest):3d}  acc={rest['Y'].mean()*100:.1f}%\")\n",
        "    print(f\"    Fisher p = {p:.4f}\")\n",
        "    print()\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# 6. Out-of-sample model comparison (LOSO)\n",
        "# ============================================================\n",
        "print(\"=\" * 60)\n",
        "print(\"6. OUT-OF-SAMPLE MODEL COMPARISON (LOSO)\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "df[\"L_sq\"] = df[\"L_s\"] ** 2\n",
        "df[\"subj_L_std\"] = df.groupby(\"subject\")[\"L_s\"].transform(\"std\")\n",
        "\n",
        "def loso_predict(formula):\n",
        "    y_all, p_all = [], []\n",
        "    for tr, te in logo.split(df, groups=groups):\n",
        "        train = df.iloc[tr].copy()\n",
        "        test = df.iloc[te].copy()\n",
        "        m = smf.logit(formula, data=train).fit(disp=0)\n",
        "        p_all.extend(m.predict(test).values)\n",
        "        y_all.extend(test[\"Y\"].values)\n",
        "    return np.array(y_all), np.array(p_all)\n",
        "\n",
        "\n",
        "models = {\n",
        "    \"A: mean only\":       \"Y ~ L_s\",\n",
        "    \"B: mean + L^2\":      \"Y ~ L_s + L_sq\",\n",
        "    \"C: mean + subj SD\":  \"Y ~ L_s + subj_L_std\",\n",
        "}\n",
        "\n",
        "results = {}\n",
        "for name, formula in models.items():\n",
        "    y_all, p_all = loso_predict(formula)\n",
        "    auc = roc_auc_score(y_all, p_all)\n",
        "    ll = log_loss(y_all, p_all)\n",
        "    br = brier_score_loss(y_all, p_all)\n",
        "    results[name] = (y_all, p_all, auc, ll, br)\n",
        "    print(f\"  {name:20s}  AUC={auc:.4f}  logloss={ll:.4f}  Brier={br:.4f}\")\n",
        "\n",
        "y_all = results[\"A: mean only\"][0]\n",
        "base_ll = log_loss(y_all, [y_all.mean()] * len(y_all))\n",
        "base_br = brier_score_loss(y_all, [y_all.mean()] * len(y_all))\n",
        "print(f\"  {'Base rate':20s}  AUC=0.5000  logloss={base_ll:.4f}  Brier={base_br:.4f}\")\n",
        "print()\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# 7. Bootstrap AUC difference (A vs C)\n",
        "# ============================================================\n",
        "print(\"=\" * 60)\n",
        "print(\"7. BOOTSTRAP AUC DIFFERENCE (A vs C)\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "y_A, p_A, auc_A, _, _ = results[\"A: mean only\"]\n",
        "y_C, p_C, auc_C, _, _ = results[\"C: mean + subj SD\"]\n",
        "assert np.array_equal(y_A, y_C)\n",
        "\n",
        "diffs = []\n",
        "for _ in range(2000):\n",
        "    idx = RNG.integers(0, len(y_A), len(y_A))\n",
        "    if len(np.unique(y_A[idx])) < 2:\n",
        "        continue\n",
        "    diffs.append(roc_auc_score(y_A[idx], p_C[idx]) - roc_auc_score(y_A[idx], p_A[idx]))\n",
        "diffs = np.array(diffs)\n",
        "\n",
        "lo, hi = np.percentile(diffs, [2.5, 97.5])\n",
        "print(f\"  AUC(A) = {auc_A:.4f}   AUC(C) = {auc_C:.4f}   diff = {auc_C - auc_A:+.4f}\")\n",
        "print(f\"  Bootstrap mean diff: {diffs.mean():+.4f}\")\n",
        "print(f\"  95% CI: [{lo:+.4f}, {hi:+.4f}]\")\n",
        "print(f\"  P(diff > 0): {(diffs > 0).mean():.4f}\")\n",
        "print()\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# 8. Threshold model\n",
        "# ============================================================\n",
        "print(\"=\" * 60)\n",
        "print(\"8. THRESHOLD MODEL (L_high at 8.75s)\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "thr = df[\"L_s\"].quantile(0.75)\n",
        "df[\"L_high\"] = (df[\"L_s\"] >= thr).astype(int)\n",
        "m_thr = smf.logit(\"Y ~ L_high\", data=df).fit(disp=0)\n",
        "print(f\"  Threshold = {thr:.2f}s\")\n",
        "print(f\"  beta = {m_thr.params['L_high']:+.4f}  p = {m_thr.pvalues['L_high']:.4f}\")\n",
        "print(f\"  Odds ratio = {np.exp(m_thr.params['L_high']):.4f}\")\n",
        "print()\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# Summary\n",
        "# ============================================================\n",
        "print(\"=\" * 60)\n",
        "print(\"SUMMARY\")\n",
        "print(\"=\" * 60)\n",
        "print(f\"  n = {len(df)} trials, {df['subject'].nunique()} subjects, \"\n",
        "      f\"accuracy = {df['Y'].mean()*100:.1f}%\")\n",
        "print(f\"  Within-subject beta  = {m4.params['L_within']:+.4f}  (p = {m4.pvalues['L_within']:.4f})\")\n",
        "print(f\"  LOSO beta            = {betas.mean():+.4f} ± {betas.std():.4f}  ({(betas<0).sum()}/{len(betas)} negative)\")\n",
        "print(f\"  r(L_std, acc)        = {r_std:+.3f}  (p = {p_std:.4f})\")\n",
        "print(f\"  r(L_mean, acc)       = {r_mean:+.3f}  (p = {p_mean:.4f})\")\n",
        "print(f\"  AUC mean-only        = {auc_A:.4f}\")\n",
        "print(f\"  AUC mean+variance    = {auc_C:.4f}   (diff = {auc_C - auc_A:+.4f}, \"\n",
        "      f\"95% CI [{lo:+.4f}, {hi:+.4f}])\")\n",
        "print(f\"  Top-quartile L accuracy = {df[df['L_s'] >= df['L_s'].quantile(0.75)]['Y'].mean()*100:.1f}%  \"\n",
        "      f\"vs rest {df[df['L_s'] < df['L_s'].quantile(0.75)]['Y'].mean()*100:.1f}%\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "-hbxbpapJeMo",
        "outputId": "810edee3-2172-4e68-a941-f44db3691602"
      },
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Loaded 444 trials from 15 subjects\n",
            "Overall accuracy: 82.9%\n",
            "L mean=7.060s  std=3.321s\n",
            "\n",
            "============================================================\n",
            "1. TRIAL-LEVEL REGRESSIONS (in-sample)\n",
            "============================================================\n",
            "  Pooled:          beta=-0.1993  p=0.0000\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.13/dist-packages/statsmodels/discrete/discrete_model.py:268: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals\n",
            "  mlefit = super().fit(\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "  Subject FE:      beta=-0.0937  p=0.0492\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/tmp/ipykernel_3294/800733946.py:46: ConvergenceWarning: The MLE may be on the boundary of the parameter space.\n",
            "  m3 = sm.MixedLM.from_formula(\"Y ~ L_s\", groups=\"subject\", data=df).fit()\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "  Mixed model:     beta=-0.0235  p=0.0003\n",
            "  Within-subject:  beta=-0.1111  p=0.0299\n",
            "\n",
            "============================================================\n",
            "2. LEAVE-ONE-SUBJECT-OUT VALIDATION\n",
            "============================================================\n",
            "  LOSO beta:  -0.1109 ± 0.0195\n",
            "  Negative:   15/15\n",
            "\n",
            "  Per held-out subject:\n",
            "    M_04: n=30  correct=28  incorrect= 2  beta=-0.1022\n",
            "    M_05: n=30  correct=21  incorrect= 9  beta=-0.1108\n",
            "    M_06: n=30  correct=24  incorrect= 6  beta=-0.1253\n",
            "    M_09: n=30  correct=18  incorrect=12  beta=-0.0769\n",
            "    M_10: n=30  correct=29  incorrect= 1  beta=-0.1102\n",
            "    M_11: n=30  correct=25  incorrect= 5  beta=-0.0887\n",
            "    M_12: n=30  correct=29  incorrect= 1  beta=-0.1049\n",
            "    M_13: n=30  correct=28  incorrect= 2  beta=-0.1129\n",
            "    M_14: n=30  correct=30  incorrect= 0  beta=-0.1098\n",
            "    M_15: n=30  correct=18  incorrect=12  beta=-0.0975\n",
            "    M_16: n=30  correct=25  incorrect= 5  beta=-0.1364\n",
            "    M_17: n=30  correct=29  incorrect= 1  beta=-0.1004\n",
            "    M_18: n=30  correct=29  incorrect= 1  beta=-0.1088\n",
            "    M_19: n=24  correct=16  incorrect= 8  beta=-0.1146\n",
            "    M_20: n=30  correct=19  incorrect=11  beta=-0.1638\n",
            "\n",
            "============================================================\n",
            "3. SUBJECT-LEVEL CORRELATIONS\n",
            "============================================================\n",
            "subject  n      acc    L_mean    L_std\n",
            "   M_04 30 0.933333  7.579167 2.279142\n",
            "   M_05 30 0.700000  7.191667 2.642233\n",
            "   M_06 30 0.800000 11.616667 2.724002\n",
            "   M_09 30 0.600000 10.100000 3.829249\n",
            "   M_10 30 0.966667  5.150000 1.257049\n",
            "   M_11 30 0.833333  8.525000 3.370991\n",
            "   M_12 30 0.966667  4.795833 1.176037\n",
            "   M_13 30 0.933333  3.666667 0.961171\n",
            "   M_14 30 1.000000  5.358333 1.809557\n",
            "   M_15 30 0.600000  9.200000 3.057742\n",
            "   M_16 30 0.833333  6.866667 2.273093\n",
            "   M_17 30 0.966667  4.400000 1.504806\n",
            "   M_18 30 0.966667  4.533333 1.107835\n",
            "   M_19 24 0.666667  8.385417 3.121828\n",
            "   M_20 30 0.633333  8.800000 3.019798\n",
            "\n",
            "  r(L_mean, acc) = -0.759  p = 0.0010\n",
            "  r(L_std,  acc) = -0.850  p = 0.0001\n",
            "  (Bonferroni threshold for 2 tests: p < 0.0250)\n",
            "\n",
            "============================================================\n",
            "4. PARTIAL CORRELATION (L_std controlling for L_mean)\n",
            "============================================================\n",
            "==============================================================================\n",
            "                 coef    std err          t      P>|t|      [0.025      0.975]\n",
            "------------------------------------------------------------------------------\n",
            "const          1.1423      0.072     15.844      0.000       0.985       1.299\n",
            "L_mean        -0.0013      0.021     -0.062      0.951      -0.047       0.044\n",
            "L_std         -0.1346      0.053     -2.527      0.027      -0.251      -0.019\n",
            "==============================================================================\n",
            "\n",
            "============================================================\n",
            "5. TAIL SPLITS\n",
            "============================================================\n",
            "  q=0.75  threshold=8.88s\n",
            "    top:  n=112  acc=67.9%\n",
            "    rest: n=332  acc=88.0%\n",
            "    Fisher p = 0.0000\n",
            "\n",
            "  q=0.90  threshold=12.00s\n",
            "    top:  n= 46  acc=63.0%\n",
            "    rest: n=398  acc=85.2%\n",
            "    Fisher p = 0.0006\n",
            "\n",
            "============================================================\n",
            "6. OUT-OF-SAMPLE MODEL COMPARISON (LOSO)\n",
            "============================================================\n",
            "  A: mean only          AUC=0.6563  logloss=0.4348  Brier=0.1347\n",
            "  B: mean + L^2         AUC=0.6552  logloss=0.4380  Brier=0.1360\n",
            "  C: mean + subj SD     AUC=0.7310  logloss=0.4078  Brier=0.1290\n",
            "  Base rate             AUC=0.5000  logloss=0.4577  Brier=0.1419\n",
            "\n",
            "============================================================\n",
            "7. BOOTSTRAP AUC DIFFERENCE (A vs C)\n",
            "============================================================\n",
            "  AUC(A) = 0.6563   AUC(C) = 0.7310   diff = +0.0747\n",
            "  Bootstrap mean diff: +0.0759\n",
            "  95% CI: [+0.0205, +0.1306]\n",
            "  P(diff > 0): 0.9960\n",
            "\n",
            "============================================================\n",
            "8. THRESHOLD MODEL (L_high at 8.75s)\n",
            "============================================================\n",
            "  Threshold = 8.88s\n",
            "  beta = -1.2407  p = 0.0000\n",
            "  Odds ratio = 0.2892\n",
            "\n",
            "============================================================\n",
            "SUMMARY\n",
            "============================================================\n",
            "  n = 444 trials, 15 subjects, accuracy = 82.9%\n",
            "  Within-subject beta  = -0.1111  (p = 0.0299)\n",
            "  LOSO beta            = -0.1109 ± 0.0195  (15/15 negative)\n",
            "  r(L_std, acc)        = -0.850  (p = 0.0001)\n",
            "  r(L_mean, acc)       = -0.759  (p = 0.0010)\n",
            "  AUC mean-only        = 0.6563\n",
            "  AUC mean+variance    = 0.7310   (diff = +0.0747, 95% CI [+0.0205, +0.1306])\n",
            "  Top-quartile L accuracy = 67.9%  vs rest 88.0%\n"
          ]
        }
      ]
    }
  ]
}